### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by JPry** [JPry/vvv-base#12]
Latest code coverage (requires Circle CI account): https://circleci.com/api/v1.1/project/github/JPry/vvv-base/latest/artifacts/0/home/ubuntu/vvv-base/code-coverage/index.html?branch=develop

### Testing goals

In `Provisioner.php`:
- [ ] 100% for `setupSite()` method (#13)
- [ ] 100% for `createBaseDir()` method (#14)
- [ ] 100% for `createNginxConfig()` method (#15)
- [ ] 100% for `getXipioBase()` method (#16)
- [ ] 100% for `hasWpContent()` method (#17)
- [ ] 100% for `removeDefaultHtdocs()` method (#18)
- [ ] 100% for `removeDefaultWpContent()` method (#19)
- [ ] as much as possible for `install*()` methods
